// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://gcbethgkkjxvcjxdojoa.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImdjYmV0aGdra2p4dmNqeGRvam9hIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjE4NTI4OTcsImV4cCI6MjA3NzQyODg5N30.GduNIFJ4_xxm9qHu10LIVbABroD-H9jYVREE27US_zc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});