name: Manual Mirror to Repo B

on:
  workflow_dispatch:  # permite rodar manualmente

jobs:
  mirror:
    runs-on: ubuntu-latest
    permissions:
      contents: write   # <-- adiciona permissão de gravação
    steps:
      - name: Checkout repositório A
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # pega todas as branches e tags

      - name: Configurar acesso ao repositório B
        env:
          MIRROR_TOKEN: ${{ secrets.MIRROR_TOKEN }}
        run: |
          git remote add mirror https://x-access-token:${MIRROR_TOKEN}@github.com/biriki99/locaservi-producao.git

      - name: Espelhar tudo para o repositório B
        run: |
          git push --mirror mirror
