name: Espelhar manualmente para produção

on:
  workflow_dispatch: # Executa apenas quando você mandar manualmente

jobs:
  mirror:
    name: Espelhar para locaservi-producao
    runs-on: ubuntu-latest

    # Permissão de escrita para o bot fazer push
    permissions:
      contents: write

    steps:
      - name: Checkout do repositório de origem (A)
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Pega o histórico completo, necessário para o espelhamento

      - name: Configurar usuário Git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          echo "✅ Etapa concluído com sucesso!"

#git remote add mirror https://${{ secrets.MIRROR_TOKEN }}@github.com/biriki99/locaservi-producao.git
#git remote add mirror https://x-access-token:${{secrets.MIRROR_TOKEN}}@github.com/biriki99/locaservi-producao.git
      - name: Adicionar remoto de destino (B)
        run: |
          echo "Adicionando remoto do repositório B..."
          git remote add mirror https://x-access-token:${{secrets.MIRROR_TOKEN}}@github.com/biriki99/locaservi-producao.git
          echo "✅ Etapa concluído com sucesso!"

      - name: Espelhar código e branches
        run: |
          echo "Enviando todos os branches e tags para o repositório de produção..."
          git push --mirror mirror
          echo "✅ Espelhamento concluído com sucesso!"

